name: 🔒 Security Vulnerability
description: Report a security vulnerability
title: "[SECURITY] "
labels: Security
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ Thank you for reporting a security vulnerability. 
        Please do not disclose it publicly until it has been fixed.
        Author: [UjjwalS](https://ujjwalsaini.dev)

  - type: input
    id: description
    attributes:
      label: Description of the vulnerability
      description: A clear and concise description of the security issue.
      placeholder: e.g., SQL injection in the login form
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Explain how this vulnerability can be reproduced.
      placeholder: |
        1. Go to '...'
        2. Use payload '...'
        3. Observe the issue
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker achieve with this vulnerability?
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Affected environment details (OS, version, etc.)
      placeholder: e.g., Ubuntu 22.04, Node.js 18

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have a suggested fix or workaround?
      placeholder: e.g., Use parameterized queries